# Generated by Django 4.1.7 on 2023-04-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0005_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.FloatField(default=450),
        ),
    ]
